### ISSUE TITLE
Could you add a source link to this repository at rubygems.org?

### ISSUE THREAD

**Issue by minad** [frantzmiccoli/Gimuby#3]
We included your gem to http://gems.sciruby.com/ and we use the source information from github for synchronization. Just log in at rubygems.org, edit the gem and add a source link. Thx!

**Comment by frantzmiccoli** [comment]
Thanks for including Gimuby.

I am not extremely familiar with gems distribution, I don't get what you expect. What source link would you like me to add? "http://gems.sciruby.com/"?

Moreover your site is mentioning a warning about the project, any idea about what causes this?

**Comment by minad** [comment]
1. go to https://rubygems.org
2. sign in
3. go to https://rubygems.org/gems/gimuby
4. click edit on the right side
5. set the source link to https://github.com/frantzmiccoli/Gimuby

**Comment by frantzmiccoli** [comment]
It should be done. I am closing this issue, feel free to ping back if something is missing for your integration.
